name: Deploy to Heroku

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest  # 実行環境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # リポジトリをチェックアウト
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15  # Herokuにデプロイ
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Heroku APIキー
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}  # Herokuアプリ名
          heroku_email: ${{ secrets.HEROKU_APP_EMAIL }}  # Herokuアカウントのメール